[package]
name = "query-lite"
version = "0.9.0"
edition = "2024"
authors = ["D4EM0N"]
categories = ["web-programming", "database"]
description = "Convert http query params to sql queries"
documentation = "https://docs.rs/query-lite"
keywords = ["http", "sql", "query"]
license = "MIT"
repository = "https://github.com/0xC0DE666/query-lite"
rust-version = "1.88"

[dependencies]
url = { version = "^2" }
indexmap = { version = "^2" }
thiserror = { version = "^2", default-features = false }

[features]
default = ["sql"]
sql = []
